# Nomad job lifecycle management via the hashicorp/nomad Terraform provider.
# Job HCL files are generated by the iac CLI into .generated/nomad/.
# Terraform submits them and tracks their lifecycle state.

# Media application jobs (one per enabled app)
resource "nomad_job" "media_app" {
  for_each = {
    for name, app in var.apps : name => app if app.enabled
  }

  jobspec = file("${path.root}/../../.generated/nomad/${each.key}.hcl")

  purge_on_destroy = true

  hcl2 {
    enabled = true
  }
}

# Reverse proxy job
resource "nomad_job" "proxy" {
  jobspec = file("${path.root}/../../.generated/nomad/proxy.hcl")

  purge_on_destroy = true

  hcl2 {
    enabled = true
  }
}

# Output job statuses
output "nomad_job_status" {
  description = "Status of all Nomad jobs"
  value = {
    for name, job in nomad_job.media_app :
    name => job.status
  }
}
